### ISSUE TITLE
Use Mandrill templates

### ISSUE THREAD

**Issue by martinjinda** [fabiancz/mandrill-nette#7]
Hello,

is it possible to use templates created in Mandrill with your plugin? In other words, use this calls – https://mandrillapp.com/api/docs/messages.php.html#method=send-template. Thanks.

**Comment by fabiancz** [comment]
I made new function sendTemplate(), which you can use:
```php
$mailer->sendTemplate($mail, 'template_name', array(
    array('name' => 'header', 'content' => 'testing header'),
));
```
